In [7]:
!pip install yfinance pandas matplotlib

Requirement already satisfied: yfinance in c:\users\srima\anaconda_projects\aqi\lib\site-packages (1.5.1)
Requirement already satisfied: pandas in c:\users\srima\anaconda_projects\aqi\lib\site-packages (2.2.3)
Requirement already satisfied: matplotlib in c:\users\srima\anaconda_projects\aqi\lib\site-packages (3.10.0)
Requirement already satisfied: numpy>=1.16.5 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: peewee>=3.16.2 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (4.2.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (3.20.0)
Requirement already satisfied: websockets>=13.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from yfinance) (16.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from curl_cffi>=0.15->yfinance) (2025.4.26)
Requirement already satisfied: rich in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from curl_cffi>=0.15->yfinance) (13.9.4)
Requirement already satisfied: pycparser in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\srima\anaconda_projects\aqi\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.0)

In [32]:
import yfinance as yf
import pandas as pd

In [33]:
import yfinance as yf
import pandas as pd

stocks = ["GME", "AMC", "TSLA"]

all_data = []

for stock in stocks:

    data = yf.download(
        stock,
        start="2021-01-01",
        end="2021-03-01",
        auto_adjust=False
    )

    # Remove MultiIndex columns
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)

    data = data.reset_index()

    data["Ticker"] = stock

    all_data.append(data)

market_data = pd.concat(all_data, ignore_index=True)

market_data.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price       Date  Adj Close   Close    High     Low    Open    Volume Ticker
0     2021-01-04     4.3125  4.3125  4.7750  4.2875  4.7500  40090000    GME
1     2021-01-05     4.3425  4.3425  4.5200  4.3075  4.3375  19846000    GME
2     2021-01-06     4.5900  4.5900  4.7450  4.3325  4.3350  24224800    GME
3     2021-01-07     4.5200  4.5200  4.8625  4.5050  4.6175  24517200    GME
4     2021-01-08     4.4225  4.4225  4.5750  4.2700  4.5450  25928000    GME

In [34]:
df.isnull().sum()

Price
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
Ticker       0
dtype: int64

In [35]:
market_data.isnull().sum()

Price
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
Ticker       0
dtype: int64

In [36]:
print(market_data.shape)

(114, 8)

In [37]:
gme = market_data[market_data["Ticker"] == "GME"]
amc = market_data[market_data["Ticker"] == "AMC"]
tsla = market_data[market_data["Ticker"] == "TSLA"]

gme.to_csv("gme_stock.csv", index=False)
amc.to_csv("amc_stock.csv", index=False)
tsla.to_csv("tsla_stock.csv", index=False)

In [41]:
print(gme.head())
print(amc.head())
print(tsla.head())

Price       Date  Adj Close   Close    High     Low    Open    Volume Ticker
0     2021-01-04     4.3125  4.3125  4.7750  4.2875  4.7500  40090000    GME
1     2021-01-05     4.3425  4.3425  4.5200  4.3075  4.3375  19846000    GME
2     2021-01-06     4.5900  4.5900  4.7450  4.3325  4.3350  24224800    GME
3     2021-01-07     4.5200  4.5200  4.8625  4.5050  4.6175  24517200    GME
4     2021-01-08     4.4225  4.4225  4.5750  4.2700  4.5450  25928000    GME
Price       Date  Adj Close      Close       High        Low       Open  \
38    2021-01-04  20.100000  20.100000  22.000000  20.000000  22.000000
39    2021-01-05  19.799999  19.799999  20.299999  19.100000  19.900000
40    2021-01-06  20.100000  20.100000  22.299999  19.700001  20.299999
41    2021-01-07  20.500000  20.500000  21.100000  20.200001  20.799999
42    2021-01-08  21.400000  21.400000  22.100000  20.700001  20.900000

Price   Volume Ticker
38     2987380    AMC
39     2814830    AMC
40     6736330    AMC
41     2615050    AMC
42     3955330    AMC
Price       Date   Adj Close       Close        High         Low        Open  \
76    2021-01-04  243.256668  243.256668  248.163330  239.063339  239.820007
77    2021-01-05  245.036667  245.036667  246.946671  239.733337  241.220001
78    2021-01-06  251.993332  251.993332  258.000000  249.699997  252.830002
79    2021-01-07  272.013336  272.013336  272.329987  258.399994  259.209991
80    2021-01-08  293.339996  293.339996  294.829987  279.463318  285.333344

Price     Volume Ticker
76     145914600   TSLA
77      96735600   TSLA
78     134100000   TSLA
79     154496700   TSLA
80     225166500   TSLA

In [42]:
gme_df = pd.read_csv("reddit_gme.csv")
amc_df = pd.read_csv("reddit_amc.csv")
tsla_df = pd.read_csv("reddit_tsla.csv")

In [43]:
print(gme_df.columns)
print(amc_df.columns)
print(tsla_df.columns)

Index(['title', 'score', 'comms_num', 'timestamp', 'date', 'text'], dtype='object')
Index(['title', 'score', 'comms_num', 'timestamp', 'date', 'text'], dtype='object')
Index(['title', 'score', 'comms_num', 'timestamp', 'date', 'text'], dtype='object')

In [44]:
print(gme_df.columns)
print(type(gme_df))

Index(['title', 'score', 'comms_num', 'timestamp', 'date', 'text'], dtype='object')
<class 'pandas.core.frame.DataFrame'>

In [45]:
gme_df[["date","text"]].head()

         date                                               text
0  2021-01-28  Math Professor Scott Steiner says the numbers ...
1  2021-01-28  Exit the system The CEO of NASDAQ pushed to ha...
2  2021-01-28  NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...
3  2021-01-28  Not to distract from GME, just thought our AMC...
4  2021-01-28  SHORT STOCK DOESN'T HAVE AN EXPIRATION DATE He...

In [46]:
gme_df["text"].sample(20)

1974     65k reinforcements coming in from /r/enlighten...
3020     Citadel just robbed EVERYONE on this sub NO ON...
6640     Why an SLV squeeze will 100% not work. First o...
2587     Set your Sell limits GME Go in and make sure y...
2283     Extra liquidity in GME and AMC Just saw the re...
14285    Inflation impulse sets off precious metals, on...
4556     Embraced my inner retard Charlie Schwann doesn...
5565     A Hypothetical of why RobinHood started pullin...
8396     GME could find its place. To all the peoples s...
11240    $TRXC (TransEnterix): already over 1B market c...
8144        💎🧠 Loop de Loop predicted. GME to infinity. 🚀
14409    God Tier DD, Buy NOW & Get Rich Monday \nSup a...
13843    GameStop won’t stop, buying GameStop! Why? I l...
5428     Hold and don’t sell!! 12 minutes after MARKER ...
5081     Bullshit. Does anyone know the GME limit? I tr...
2328     FUCK STASH Put in orders for GME NOK and BB la...
10407    JUST LOST MY COLLEGE TUITION ON GME - HELP ME ...
11176    Tanker Stocks are Smooth Sailing Sea shanties ...
8389     For the people who holding and don't feel the ...
10725    Change of dialect. Will wsb speak with a new t...
Name: text, dtype: object

In [48]:
gme_df["text"].isnull().sum()
amc_df["text"].isnull().sum()
tsla_df["text"].isnull().sum()

np.int64(0)

In [49]:
gme_df["text"].str.contains(
    r"\[deleted\]|\[removed\]",
    case=False,
    na=False
).sum()

np.int64(0)

In [50]:
amc_df["text"].str.contains(
    r"\[deleted\]|\[removed\]",
    case=False,
    na=False
).sum()

np.int64(0)

In [51]:
tsla_df["text"].str.contains(
    r"\[deleted\]|\[removed\]",
    case=False,
    na=False
).sum()

np.int64(0)

In [52]:
print("GME:", len(gme_df))
print("AMC:", len(amc_df))
print("TSLA:", len(tsla_df))

GME: 14745
AMC: 5161
TSLA: 1078

In [53]:
gme_df.columns

Index(['title', 'score', 'comms_num', 'timestamp', 'date', 'text'], dtype='object')